# Generated by Django 5.2.5 on 2026-02-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenue', '0002_paymentaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorwallet',
            name='pending_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
