# Generated by Django 5.2.5 on 2026-01-26 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('courses', '0008_remove_lesson_video_file_alter_lesson_content_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messagereadstatus',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='messagereadstatus',
            name='message',
        ),
        migrations.RemoveField(
            model_name='messagereadstatus',
            name='user',
        ),
        migrations.RemoveField(
            model_name='useronlinestatus',
            name='current_room',
        ),
        migrations.RemoveField(
            model_name='useronlinestatus',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveIndex(
            model_name='chatroom',
            name='chat_rooms_room_ty_a475b2_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_room_id_b9c732_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_sender__e614c8_idx',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='is_edited',
            new_name='is_system',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='message',
            name='edited_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='file_url',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_type',
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='courses.course'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['is_active'], name='chat_rooms_is_acti_8486a3_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', 'created_at'], name='chat_messag_room_id_cc7f0e_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender'], name='chat_messag_sender__e8b05b_idx'),
        ),
        migrations.DeleteModel(
            name='MessageReadStatus',
        ),
        migrations.DeleteModel(
            name='UserOnlineStatus',
        ),
    ]
