# Generated by Django 5.2.5 on 2026-01-31 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livesession', '0002_livesession_allow_early_join_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livesession',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
    ]
