# Generated by Django 5.2.5 on 2025-08-12 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='coursecategory',
            name='slug',
        ),
    ]
