# Generated by Django 5.2.5 on 2026-01-16 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lesson_video_file_coursecertificate_lessonprogress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='content_url',
            new_name='video_url',
        ),
        migrations.AddField(
            model_name='lesson',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_source',
            field=models.CharField(blank=True, choices=[('youtube', 'YouTube / External'), ('upload', 'Uploaded Video')], max_length=20, null=True),
        ),
    ]
