# Generated by Django 5.2.5 on 2026-01-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_rename_content_url_lesson_video_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video_file',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video'), ('text', 'Text')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_source',
            field=models.CharField(blank=True, choices=[('youtube', 'YouTube'), ('cloud', 'Cloudinary')], max_length=20, null=True),
        ),
    ]
