# Generated by Django 5.2.5 on 2026-02-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in seconds', null=True),
        ),
    ]
