# Generated by Django 5.2.5 on 2026-02-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_lesson_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='watched_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
