# Generated by Django 5.2.5 on 2026-01-22 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseembedding',
            name='embedding',
        ),
    ]
