# Generated by Django 5.2.5 on 2026-01-13 16:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_coursepurchase_is_paid_order_purchase_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='pdf_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='invoices'),
        ),
    ]
