# Generated by Django 5.2.5 on 2026-03-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_invoice_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepurchase',
            name='progress_locked',
            field=models.BooleanField(default=False),
        ),
    ]
