# Generated by Django 5.2.5 on 2026-03-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_coursepurchase_progress_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='pdf_file',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
